# Generated by Django 5.1 on 2024-09-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('views', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('comments', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='playlists',
            options={'verbose_name_plural': 'Playlists'},
        ),
    ]
