version: '3.8'

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=mock_youtube
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"

  web:
    build: ./
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    links:
      - postgres:postgres

volumes:
  postgres_data:
networks:
  app-network:
